otherWords =['i'
            ,'is'
            ,'atmospheric'
            ,'as'
            ,'there'
            ,'not'
            ,'was'
            ,'it'
            ,'isn\'t'
            ,'off'
            ,'a'
            ,'quite'
            ,'because'
            ,'such'
            ,'oh'
            ,'really'
            ,'but'
            ,'from','century','streets','literally','my']